
from django.urls import path

from . import views

urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("", views.dashboard, name="dashboard"),
    path("weekly-summary/", views.weekly_summary, name="weekly_summary"),
    path("search/live/", views.global_search, name="global_search"),
    path("notifications/check/", views.notifications_check, name="notifications_check"),
    path("notifications/mark-read/", views.notifications_mark_read, name="notifications_mark_read"),
    path("letters/", views.letters, name="letters"),
    path("letters/save/", views.letters_save, name="letters_save"),
    path("branch/<str:branch>/<str:store_type>/", views.branch_view, name="branch"),
    path("store/<int:store_id>/", views.store_detail, name="store_detail"),
    path("store/<int:store_id>/duplicate/", views.duplicate_store, name="duplicate_store"),
    path("store/<int:store_id>/archive/", views.archive_store, name="archive_store"),
    path("store/<int:store_id>/kanban-status/", views.update_store_kanban_status, name="update_store_kanban_status"),
    path("store/<int:store_id>/tasks-panel/", views.store_tasks_panel, name="store_tasks_panel"),
    path("store/<int:store_id>/task/add/", views.add_task, name="add_task"),
    path("task/<int:task_id>/status/", views.update_task_status, name="update_task_status"),
    path("task/<int:task_id>/due-date/", views.update_task_due_date, name="update_task_due_date"),
    path("task/<int:task_id>/icon/", views.update_task_icon, name="update_task_icon"),
    path("task/<int:task_id>/toggle-anchor/", views.toggle_task_anchor, name="toggle_task_anchor"),
    path("task/<int:task_id>/move/<str:direction>/", views.move_task, name="move_task"),
    path("task/<int:task_id>/subtask/add/", views.add_subtask, name="add_subtask"),
    path("task/<int:task_id>/delete/", views.delete_task, name="delete_task"),
    path("store/<int:store_id>/log/add/", views.add_store_log, name="add_store_log"),
    path("log/<int:log_id>/edit/", views.edit_store_log, name="edit_store_log"),
    path("log/<int:log_id>/delete/", views.delete_store_log, name="delete_store_log"),
    path("log/<int:log_id>/file/", views.add_store_log_file, name="add_store_log_file"),
    path("logfile/<int:file_id>/delete/", views.delete_store_log_file, name="delete_store_log_file"),
    path("store/<int:store_id>/report/collect/", views.collect_report, name="collect_report"),
    path("report/<int:report_id>/save/", views.save_report, name="save_report"),
    path("report/<int:report_id>/photo/", views.add_photo, name="add_photo"),
    path("photo/<int:photo_id>/delete/", views.delete_photo, name="delete_photo"),
    path("notes/", views.notes_page, name="notes"),
    path("notes/add/", views.add_note, name="add_note"),
    path("task/<int:task_id>/note/add/", views.add_task_note, name="add_task_note"),
    path("note/<int:note_id>/delete/", views.delete_note, name="delete_note"),
    path("note/<int:note_id>/edit/", views.edit_note, name="edit_note"),
    path("note/<int:note_id>/file/", views.add_note_file, name="add_note_file"),
    path("notefile/<int:file_id>/delete/", views.delete_note_file, name="delete_note_file"),
    path("contacts/", views.contacts_page, name="contacts"),
    path("store/<int:store_id>/contact/add/", views.add_contact, name="add_contact"),
    path("contact/add/", views.add_contact_no_store, name="add_contact_no_store"),
    path("contact/<int:contact_id>/delete/", views.delete_contact, name="delete_contact"),
    path("store/<int:store_id>/problem/add/", views.add_problem, name="add_problem"),
    path("problem/<int:problem_id>/toggle/", views.toggle_problem, name="toggle_problem"),
    path("problem/<int:problem_id>/delete/", views.delete_problem, name="delete_problem"),
    path("ai/ask/", views.ai_ask, name="ai_ask"),
    path("ai/test/", views.ai_test, name="ai_test"),
    path("kb/", views.kb_list, name="kb_list"),
    path("kb/add/", views.kb_add, name="kb_add"),
    path("kb/category/add/", views.kb_category_add, name="kb_category_add"),
    path("kb/category/<int:category_id>/", views.kb_category_detail, name="kb_category_detail"),
    path("kb/category/<int:category_id>/file/", views.kb_category_add_file, name="kb_category_add_file"),
    path("kbcategoryfile/<int:file_id>/delete/", views.kb_category_delete_file, name="kb_category_delete_file"),
    path("kb/import/", views.kb_import, name="kb_import"),
    path("kb/<int:article_id>/", views.kb_detail, name="kb_detail"),
    path("kb/<int:article_id>/edit/", views.kb_edit, name="kb_edit"),
    path("kb/<int:article_id>/delete/", views.kb_delete, name="kb_delete"),
    path("kb/<int:article_id>/image/", views.kb_upload_image, name="kb_upload_image"),
    path("kb/<int:article_id>/file/", views.kb_add_file, name="kb_add_file"),
    path("kbfile/<int:file_id>/delete/", views.kb_delete_file, name="kb_delete_file"),
    path("kb/ai-search/", views.kb_ai_search, name="kb_ai_search"),
    path("logs/", views.logs_page, name="logs_page"),
    path("logs/download/", views.logs_download, name="logs_download"),
    path("kb/<int:article_id>/download/docx/", views.kb_download_docx, name="kb_download_docx"),
    path("kb/<int:article_id>/download/txt/", views.kb_download_txt, name="kb_download_txt"),
    path("kb/<int:article_id>/print/", views.kb_print, name="kb_print"),
    path("telegram/send-today/", views.telegram_send_today, name="telegram_send_today"),

    path("store/<int:store_id>/checklist/add/", views.add_checklist_item, name="add_checklist_item"),
    path("checklist/<int:item_id>/toggle/", views.toggle_checklist_item, name="toggle_checklist_item"),
    path("checklist/<int:item_id>/delete/", views.delete_checklist_item, name="delete_checklist_item"),
    path("store/<int:store_id>/checklist/fill-template/", views.fill_checklist_template, name="fill_checklist_template"),

    path("note/<int:note_id>/archive/", views.archive_note, name="archive_note"),
    path("notes/archive/", views.notes_archive_page, name="notes_archive"),

    path("salary/", views.salary_page, name="salary_page"),
    path("salary/oklad/", views.update_oklad, name="update_oklad"),
    path("salary/bonus/add/", views.add_bonus, name="add_bonus"),
    path("salary/bonus/<int:bonus_id>/delete/", views.delete_bonus, name="delete_bonus"),

    path("reconstructions/", views.reconstructions_page, name="reconstructions_page"),
    path("reconstructions/add/", views.add_reconstruction, name="add_reconstruction"),
    path("reconstructions/<int:record_id>/toggle-paid/", views.toggle_reconstruction_paid, name="toggle_reconstruction_paid"),
    path("reconstructions/<int:record_id>/delete/", views.delete_reconstruction, name="delete_reconstruction"),
    path("reconstructions/<int:record_id>/doc/", views.add_reconstruction_doc, name="add_reconstruction_doc"),
    path("reconstructions/doc/<int:doc_id>/delete/", views.delete_reconstruction_doc, name="delete_reconstruction_doc"),

    path("budgets/", views.budgets_page, name="budgets_page"),
    path("budgets/add/", views.add_budget, name="add_budget"),
    path("budgets/contractors/", views.budget_contractors, name="budget_contractors"),
    path("budgets/contractors/save/", views.budget_contractors_save, name="budget_contractors_save"),
    path("budgets/<int:calc_id>/", views.budget_detail, name="budget_detail"),
    path("budgets/<int:calc_id>/save/", views.budget_save, name="budget_save"),
    path("budgets/<int:calc_id>/archive/", views.toggle_budget_archived, name="toggle_budget_archived"),
    path("budgets/<int:calc_id>/delete/", views.delete_budget, name="delete_budget"),
    path("budgets/<int:calc_id>/to-reconstruction/", views.budget_to_reconstruction, name="budget_to_reconstruction"),

    path("store/<int:store_id>/router-config/save/", views.save_router_config, name="save_router_config"),
    path("store/<int:store_id>/router-config/download/", views.download_router_config, name="download_router_config"),
    path("router-config/template/", views.router_config_template, name="router_config_template"),

    path("store/<int:store_id>/device-ips/recalc/", views.recalc_device_ips, name="recalc_device_ips"),
    path("store/<int:store_id>/device-ips/save/", views.save_device_ips, name="save_device_ips"),

    path("store/<int:store_id>/ascn/regenerate/", views.regenerate_ascn_rows, name="regenerate_ascn_rows"),
    path("store/<int:store_id>/ascn/save/", views.save_ascn_rows, name="save_ascn_rows"),
]


