# Generated by Django 5.0.6 on 2026-07-26 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_text', models.TextField(blank=True, verbose_name='Черновик')),
                ('final_text', models.TextField(blank=True, verbose_name='Итоговый отчёт')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Отчёт',
                'verbose_name_plural': 'Отчёты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('szf', 'Филиал 1'), ('uf', 'Филиал 2'), ('pf', 'Филиал 3'), ('cf', 'Филиал 4')], max_length=10, verbose_name='Филиал')),
                ('store_type', models.CharField(choices=[('opening', 'Открытие'), ('reconstruction', 'Реконструкция')], max_length=20, verbose_name='Тип')),
                ('number', models.CharField(max_length=50, verbose_name='№ объекта')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Адрес')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Регион')),
                ('contact', models.CharField(blank=True, max_length=200, verbose_name='Контакт / подрядчик')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reports/%Y/%m/%d/', verbose_name='Фото')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='board.report')),
            ],
            options={
                'verbose_name': 'Фото отчёта',
                'verbose_name_plural': 'Фото отчётов',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='report',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='board.store'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Задача')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Срок')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('progress', 'В работе'), ('waiting', 'Ждём подрядчика'), ('done', 'Готово')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='board.store')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['due_date', '-created_at'],
            },
        ),
    ]
