# Generated by Django 5.0.6 on 2026-07-30 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_article_articlefile_articleimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('month', models.IntegerField(verbose_name='Месяц')),
                ('amount', models.IntegerField(verbose_name='Сумма премии до вычета НДФЛ')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='За что')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Премия',
                'verbose_name_plural': 'Премии',
                'ordering': ['-year', '-month', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconstructionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(blank=True, choices=[('szf', 'Филиал 1'), ('uf', 'Филиал 2'), ('pf', 'Филиал 3'), ('cf', 'Филиал 4')], max_length=10, verbose_name='Филиал')),
                ('store_number', models.CharField(max_length=50, verbose_name='№ объекта')),
                ('reconstruction_date', models.DateField(blank=True, null=True, verbose_name='Дата реконструкции')),
                ('expected_amount', models.IntegerField(blank=True, null=True, verbose_name='Ожидаемая премия')),
                ('paid', models.BooleanField(default=False, verbose_name='Выплачено')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Дата выплаты')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Реконструкция (премии)',
                'verbose_name_plural': 'Реконструкции (премии)',
                'ordering': ['paid', '-reconstruction_date'],
            },
        ),
        migrations.CreateModel(
            name='SalarySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_oklad', models.IntegerField(default=90000, verbose_name='Оклад до вычета НДФЛ')),
                ('ndfl_percent', models.DecimalField(decimal_places=1, default=13, max_digits=4, verbose_name='НДФЛ, %')),
            ],
            options={
                'verbose_name': 'Настройки зарплаты',
                'verbose_name_plural': 'Настройки зарплаты',
            },
        ),
        migrations.AddField(
            model_name='note',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='В архиве'),
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Пункт')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Отмечено')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='board.store')),
            ],
            options={
                'verbose_name': 'Пункт чек-листа',
                'verbose_name_plural': 'Чек-лист',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReconstructionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='reconstruction_docs/%Y/%m/%d/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='board.reconstructionrecord')),
            ],
            options={
                'verbose_name': 'Документ реконструкции',
                'verbose_name_plural': 'Документы реконструкций',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
