# Generated by Django 5.0.6 on 2026-08-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_task_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='Ключ')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('header', models.CharField(blank=True, default='', max_length=200, verbose_name='Шапка письма')),
                ('subject', models.CharField(blank=True, default='', max_length=300, verbose_name='Тема письма')),
                ('recipients', models.TextField(blank=True, default='', verbose_name='Получатели')),
                ('columns', models.JSONField(default=list, verbose_name='Столбцы')),
                ('rows', models.JSONField(default=list, verbose_name='Строки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Компания (письма)',
                'verbose_name_plural': 'Компании (письма)',
                'ordering': ['order', 'id'],
            },
        ),
    ]
