# Generated by Django 5.0.6 on 2026-08-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0014_lettercompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='lettercompany',
            name='is_store_contractor',
            field=models.BooleanField(default=False, verbose_name='Подрядчик при создании магазина'),
        ),
        migrations.AddField(
            model_name='store',
            name='access_points_count',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Кол-во точек доступа'),
        ),
        migrations.AddField(
            model_name='store',
            name='area_format',
            field=models.CharField(blank=True, choices=[('200/300', '200/300'), ('400', '400'), ('500/600', '500/600')], default='', max_length=20, verbose_name='Формат по площади'),
        ),
        migrations.AddField(
            model_name='store',
            name='columns_count',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Кол-во колонок'),
        ),
        migrations.AddField(
            model_name='store',
            name='columns_type',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Тип колонок'),
        ),
        migrations.AddField(
            model_name='store',
            name='contractors',
            field=models.JSONField(blank=True, default=list, verbose_name='Подрядчики (для писем)'),
        ),
        migrations.AddField(
            model_name='store',
            name='has_meat_scale',
            field=models.BooleanField(default=False, verbose_name='Весы «мясо» на объекте'),
        ),
        migrations.AddField(
            model_name='store',
            name='kso_count',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Кол-во КСО'),
        ),
    ]
