# Generated by Django 5.0.6 on 2026-08-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0018_fix_oborudovanie_dash'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='cash_count',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Кол-во касс'),
        ),
        migrations.AlterField(
            model_name='store',
            name='area_format',
            field=models.CharField(blank=True, choices=[('200', '200'), ('300', '300'), ('400', '400'), ('500/600', '500/600')], default='', max_length=20, verbose_name='Формат по площади'),
        ),
    ]
