# Generated by Django 5.0.6 on 2026-08-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0020_letters_more_autofill_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('progress', 'В работе'), ('waiting', 'Ждём подрядчика'), ('done', 'Готово')], default='progress', max_length=20, verbose_name='Статус'),
        ),
    ]
