# Generated by Django 5.0.6 on 2026-08-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0022_migrate_new_status_to_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_type',
            field=models.CharField(choices=[('opening', 'Открытие'), ('reconstruction', 'Реконструкция'), ('extra', 'Доп. работы'), ('closing', 'Закрытие')], max_length=20, verbose_name='Тип'),
        ),
    ]
