# Generated by Django 5.0.6 on 2026-08-02 11:40

from django.db import migrations, models

DEFAULT_COLUMNS = [
    {"name": "Филиал"},
    {"name": "№ объекта"},
    {"name": "Адрес"},
    {"name": "Регион"},
]

ACCOUNT_TABS = ["Система 1", "Система 2", "Система 3", "Плеер", "СБП"]


def create_account_tabs(apps, schema_editor):
    LetterCompany = apps.get_model("board", "LetterCompany")
    existing_names = set(LetterCompany.objects.filter(page="accounts").values_list("name", flat=True))
    base_order = LetterCompany.objects.count()
    for i, name in enumerate(ACCOUNT_TABS):
        if name in existing_names:
            continue
        LetterCompany.objects.create(
            key=f"c_accounts_{name}",
            page="accounts",
            name=name,
            order=base_order + i,
            header="",
            subject=f"Создание учёток — {name}",
            recipients="",
            columns=DEFAULT_COLUMNS,
            rows=[["", "", "", ""]],
            is_store_contractor=False,
        )


def remove_account_tabs(apps, schema_editor):
    LetterCompany = apps.get_model("board", "LetterCompany")
    LetterCompany.objects.filter(page="accounts", name__in=ACCOUNT_TABS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0023_store_type_closing'),
    ]

    operations = [
        migrations.AddField(
            model_name='lettercompany',
            name='page',
            field=models.CharField(choices=[('schedules', 'Графики работ'), ('accounts', 'Создание учёток')], default='schedules', max_length=20, verbose_name='Страница'),
        ),
        migrations.RunPython(create_account_tabs, remove_account_tabs),
    ]
