# Generated by Django 5.0.6 on 2026-08-03 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0024_lettercompany_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Проблема')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Решено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Решено когда')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='board.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Проблема',
                'verbose_name_plural': 'Проблемы',
                'ordering': ['is_resolved', '-created_at'],
            },
        ),
    ]
