# Generated by Django 5.0.6 on 2026-08-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0027_contractor_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='due_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время'),
        ),
        migrations.AddField(
            model_name='note',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Уведомление отправлено'),
        ),
    ]
