# Generated by Django 5.0.6 on 2026-08-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0028_note_due_time_note_notified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='kanban_status',
            field=models.CharField(choices=[('new', 'Новый'), ('progress', 'В работе'), ('review', 'Проверка'), ('open', 'Открыт')], default='new', max_length=20, verbose_name='Стадия'),
        ),
    ]
