# Generated by Django 5.0.6 on 2026-08-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0029_store_kanban_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_type',
            field=models.CharField(choices=[('opening', 'Новые Магазины'), ('reconstruction', 'Реконструкция'), ('extra', 'Доп. работы'), ('closing', 'Закрытие')], max_length=20, verbose_name='Тип'),
        ),
    ]
