# Generated by Django 5.0.6 on 2026-08-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0030_rename_opening_to_new_stores'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Раздел'),
        ),
    ]
