# Generated by Django 5.0.6 on 2026-08-05 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0033_seed_kb_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouterConfigTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_text', models.TextField(blank=True, verbose_name='Текст шаблона')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Шаблон конфига роутера',
                'verbose_name_plural': 'Шаблон конфига роутера',
            },
        ),
        migrations.CreateModel(
            name='StoreRouterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.JSONField(blank=True, default=dict, verbose_name='Значения полей')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='router_config', to='board.store')),
            ],
        ),
    ]
