# Generated by Django 5.0.6 on 2026-08-05 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0034_routerconfigtemplate_storerouterconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='branch',
            field=models.CharField(blank=True, choices=[('szf', 'Филиал 1'), ('uf', 'Филиал 2'), ('pf', 'Филиал 3'), ('cf', 'Филиал 4')], max_length=10, verbose_name='Филиал'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='board.store'),
        ),
    ]
