# Generated by Django 5.0.6 on 2026-08-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0035_contact_optional_store_and_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Выполнено'),
        ),
    ]
