# Generated by Django 5.0.6 on 2026-08-06 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0036_task_completed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='KbCategoryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='kb_category_files/%Y/%m/%d/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='board.kbcategory')),
            ],
            options={
                'verbose_name': 'Файл категории базы знаний',
                'verbose_name_plural': 'Файлы категорий базы знаний',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
