# Generated by Django 5.0.6 on 2026-08-07 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0037_kbcategoryfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreDeviceIPConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.JSONField(blank=True, default=dict, verbose_name='Значения адресов устройств')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='device_ip_config', to='board.store')),
            ],
        ),
    ]
