# Generated by Django 5.0.6 on 2026-08-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0038_storedeviceipconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='reconstruction_kind',
            field=models.CharField(blank=True, choices=[('full', 'Полная'), ('partial', 'Частичная'), ('mini', 'Мини')], default='', max_length=20, verbose_name='Вид реконструкции'),
        ),
    ]
