# Generated by Django 5.0.6 on 2026-08-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0039_store_reconstruction_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='cluster',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Кластер'),
        ),
        migrations.AddField(
            model_name='store',
            name='contractor_kto',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Подрядчик КТО'),
        ),
        migrations.AddField(
            model_name='store',
            name='contractor_pnr',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Подрядчик ПНР'),
        ),
        migrations.AddField(
            model_name='store',
            name='contractor_scs',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Подрядчик СКС'),
        ),
        migrations.AddField(
            model_name='store',
            name='ibp_count',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Кол-во ИБП'),
        ),
        migrations.AddField(
            model_name='store',
            name='kpp',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='КПП'),
        ),
        migrations.AddField(
            model_name='store',
            name='license_number',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Лицензия для касс'),
        ),
        migrations.AddField(
            model_name='store',
            name='provider',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Провайдер'),
        ),
    ]
