# Generated by Django 5.0.6 on 2026-08-11 11:15

from django.db import migrations, models

# Столбцы таблицы графика работ для новых компаний-подрядчиков (см. LetterCompany.columns).
LETTER_COLUMNS = [
    {"name": "Филиал", "autofill": "branch"},
    {"name": "№ объекта", "autofill": "number"},
    {"name": "Адрес", "autofill": "address"},
    {"name": "Регион", "autofill": "region"},
    {"name": "Кол-во касс", "autofill": "cash_count"},
    {"name": "Кол-во КСО", "autofill": "kso_count"},
    {"name": "Формат по площади", "autofill": "area_format"},
    {"name": "Кол-во колонок", "autofill": "columns_count"},
    {"name": "Тип колонок", "autofill": "columns_type"},
    {"name": "TUNIP"},
    {"name": "Внутренние IP адреса"},
    {"name": "Дата СКС", "autofill": "task_date:СКС"},
    {"name": "Дата ПНР", "autofill": "task_date:ПНР"},
    {"name": "Дата ВПК-2", "autofill": "task_date:ВПК-2"},
    {"name": "Дата открытия", "autofill": "task_date:Открытие"},
    {"name": "Подрядчик СКС"},
    {"name": "Подрядчик ПНР"},
]


def create_letter_companies(apps, schema_editor):
    LetterCompany = apps.get_model("board", "LetterCompany")
    LetterCompany.objects.create(
        key="biznes_sodeystvie", name="Бизнес Содействие", page="schedules", order=7,
        is_store_contractor=True, columns=LETTER_COLUMNS, rows=[],
    )
    LetterCompany.objects.create(
        key="data_krat", name="Дата Крат", page="schedules", order=8,
        is_store_contractor=True, columns=LETTER_COLUMNS, rows=[],
    )


def remove_letter_companies(apps, schema_editor):
    LetterCompany = apps.get_model("board", "LetterCompany")
    LetterCompany.objects.filter(key__in=["biznes_sodeystvie", "data_krat"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0040_store_excel_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='contractor_kto',
        ),
        migrations.RemoveField(
            model_name='store',
            name='contractor_pnr',
        ),
        migrations.RemoveField(
            model_name='store',
            name='contractor_scs',
        ),
        migrations.AlterField(
            model_name='store',
            name='contact',
            field=models.CharField(blank=True, choices=[('Союз-76', 'Союз-76'), ('Принтград', 'Принтград'), ('НВ', 'НВ'), ('Дата Крат', 'Дата Крат'), ('Бизнес Содействие', 'Бизнес Содействие')], max_length=200, verbose_name='Подрядчик'),
        ),
        migrations.RunPython(create_letter_companies, remove_letter_companies),
    ]
