# Generated by Django 5.0.6 on 2026-08-11 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0041_store_contact_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='fsrar_id',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='FSRAR_ID'),
        ),
        migrations.AddField(
            model_name='store',
            name='locality',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Населённый пункт'),
        ),
        migrations.CreateModel(
            name='StoreCashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('number', models.CharField(blank=True, default='', max_length=20, verbose_name='Номер КСО')),
                ('loymax_data', models.TextField(blank=True, default='', verbose_name='LOYMAX posid/login/password')),
                ('sbp_terminal', models.CharField(blank=True, default='', max_length=50, verbose_name='Номер терминала СБП')),
                ('sbp_link', models.CharField(blank=True, default='', max_length=255, verbose_name='Кассовая ссылка СБП')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_registers', to='board.store')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
