# Generated by Django 5.0.6 on 2026-08-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0042_store_fsrar_id_store_locality_storecashregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storelog',
            name='source',
            field=models.CharField(choices=[('web', 'Сайт'), ('tg', 'Telegram'), ('report', 'Из старого отчёта'), ('voice', 'Голосовой ассистент')], default='web', max_length=10, verbose_name='Источник'),
        ),
    ]
