# Generated by Django 5.0.6 on 2026-08-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0043_storelog_source_add_voice'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='extra_kind',
            field=models.CharField(blank=True, choices=[('extra_kso', 'Установка доп. КСО')], default='', max_length=20, verbose_name='Вид работ'),
        ),
    ]
