# Generated by Django 5.0.6 on 2026-08-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0044_store_extra_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True, verbose_name='ID письма')),
                ('processed_at', models.DateTimeField(auto_now_add=True, verbose_name='Обработано')),
            ],
            options={
                'verbose_name': 'Обработанное письмо',
                'verbose_name_plural': 'Обработанные письма',
            },
        ),
    ]
